-- AlterTable
ALTER TABLE "Bug" ALTER COLUMN "issue_created" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "issue_created" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "issue_closed" SET DATA TYPE TIMESTAMP(3);
